// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jephtaoljboctmruoaic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplcGh0YW9samJvY3RtcnVvYWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDUwNzMsImV4cCI6MjA1MTgyMTA3M30.WhSpaDGWulBAQF83SNgFwYOVUe4LqURTK09YeIrP2I4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);